#22 | Add getOrCreateIndex functionality
meilisearch/meilisearch-java pull request #45
Opened 2020-10-27 08:58 UTC by arjunrc143

2020-10-27 11:33 UTC, eskombro commented
Hi @arjunrc143 

Thanks for your PR. It is important that in the `getoOrCreateIndex` method we catch the Exception only if the error corresponds to [an index that exists already](https://docs.meilisearch.com/errors/#index_already_exists). Otherwise we shouldn't proceed as we do not necessarily know where the problem is coming from. You can check in the MeiliSearch response if the errorCode corresponds to `index_already_exists`.

This will be updated later when we implement a Custom error handler in #7 

Can you please add this check?

2020-10-27 11:34 UTC, eskombro commented
Also, please link the issue. You can add a comment in your pr like this

```
Closes #22 
```

2020-10-27 12:41 UTC, eskombro requested changes

2020-10-27 12:41 UTC, eskombro commented on src/main/java/com/meilisearch/sdk/Client.java
> +	 * @return Meilisearch API response
This function returns an index Instance, not the http response :)

2020-10-27 13:31 UTC, eskombro commented on src/main/java/com/meilisearch/sdk/Client.java
> +	 * @return Meilisearch API response
```suggestion
	 * @return Index instance
```

2020-10-27 13:31 UTC, eskombro commented on src/main/java/com/meilisearch/sdk/Client.java
> +	 * @return Meilisearch API response
```suggestion
	 * @return Index instance
```

2020-10-27 14:12 UTC, arjunrc143 commented
> Hi @arjunrc143
> 
> Thanks for your PR. It is important that in the `getoOrCreateIndex` method we catch the Exception only if the error corresponds to [an index that exists already](https://docs.meilisearch.com/errors/#index_already_exists). Otherwise we shouldn't proceed as we do not necessarily know where the problem is coming from. You can check in the MeiliSearch response if the errorCode corresponds to `index_already_exists`.
> 
> This will be updated later when we implement a Custom error handler in #7
> 
> Can you please add this check?

Done

2020-10-27 14:12 UTC, arjunrc143 commented
closes #22

2020-10-27 16:37 UTC, eskombro commented
> closes #22

I think this must be done in the description :)

I linked it anyways !

2020-10-27 16:42 UTC, eskombro commented
This PR seems good! Just need to add a few integration tests ! For example:

- Use getOrCreateIndex() and check that the index is created
- Use getOrCreateIndex() with an existing index and check that no error is thrown and the index is returned
- Use getOrCreateIndex() 2 or three times in a row...

2020-10-28 04:24 UTC, arjunrc143 commented
@eskombro I have added the integration tests. Please check.

2020-10-28 04:38 UTC, arjunrc143 commented
2 integration tests are failing. Will check that.

2020-10-29 00:13 UTC, eskombro commented
I checked what's going on, and the problem is that when you get an `index_already_exists` error, the SDK is throwing an IOException with the message 

```
Server returned HTTP response code: 400 for URL: http://localhost:7700/indexes
```

So the check you implemented for the error catching doesn't work. This problem is coming from what `createIndex()` returns in case of failure, and so, not your bad or any propblem in your PR at all actually.

I'll fix this since I'm implementing a basic error handler, and let you know so you can rebase your branch and it should work fine!

Glad we did those tests 👍

2020-10-29 04:17 UTC, arjunrc143 commented
@eskombro Cool. Let me know once this gets fixed. Thanks!

2020-11-04 00:42 UTC, eskombro requested changes
Hey!

We can already use custom Exceptions, Can you please rebase your branch on master?

I did a suggestion on how to check for the MeiliSearchApiException in this method which is already tested! 

ALSO:

Can you please create a `getOrCreateIndex(String uid)` method without a primaryKey, which calls `getOrCreateIndex(String uid, null)` ?

```java
public Index getOrCreateIndex(String uid) throws Exception {
	return getOrCreateIndex(uid, null);
}
```

`primaryKey` should be optional!

After this PR will be ready to merge! 🎉

2020-11-04 00:42 UTC, eskombro commented on src/main/java/com/meilisearch/sdk/Client.java
> +		}
```suggestion
		try {
			return this.createIndex(uid, primaryKey);
		} catch (MeiliSearchApiException e) {
			if(e.getErrorCode().equals("index_already_exists")) {
				return this.getIndex(uid);
			}
			throw e;
		}
```

2020-11-04 13:44 UTC, arjunrc143 commented
> Hey @arjunrc143!
> 
> We can already use custom Exceptions, Can you please rebase your branch on master?
> 
> I did a suggestion on your code, on how to check the `MeiliSearchApiException` errorCode in this method which is already tested!
> 
> ALSO:
> 
> Can you please create a `getOrCreateIndex(String uid)` method without a primaryKey, which calls `getOrCreateIndex(String uid, null)` ?
> 
> ```java
> public Index getOrCreateIndex(String uid) throws Exception {
> 	return getOrCreateIndex(uid, null);
> }
> ```
> 
> `primaryKey` should be optional!
> 
> After this PR will be ready to merge! 🎉

@eskombro This is done. Can you please review it?

2020-11-05 15:58 UTC, eskombro approved these changes
Thanks! 🎉

2020-11-05 16:03 UTC, merged