Update version for the next release (v0.8.0)
meilisearch/meilisearch-java pull request #488
Opened 2022-11-09 15:27 UTC by alallema

This version includes a major redesign of the SDK. ([#425](https://github.com/meilisearch/meilisearch-java/pull/425)) [@alallema](https://github.com/alallema)

## ⚠️ Breaking changes

* Use `OkHttp` library by default for the Meilisearch client (#449) @alallema
* Rename `getAllIndexes` method in `getIndexes` (#477) @alallema

## 🚀 Enhancements

* Replaced traditional getter setter by `@Getter` `@Setter` from Lombok library ([#385](https://github.com/meilisearch/meilisearch-java/pull/385)) [@ghousek1](https://github.com/ghousek1)
* Improve Docker configuration in the package ([#399](https://github.com/meilisearch/meilisearch-java/pull/399))
* Add code-coverage tool (jacoco) ([#422](https://github.com/meilisearch/meilisearch-java/pull/422)) [@brunoocasali](https://github.com/brunoocasali)
* Refactoring:
    * Rewriting of the Error Handler ([#438](https://github.com/meilisearch/meilisearch-java/pull/438)) [@alallema](https://github.com/alallema)
        * Like the other SDKs, this one now contains `MeilisearchApiError`, `MeiliSearchCommunicationError` and `MeilsiearchTimeoutError`.
    * Rewriting of the Json Handler
        * Offering the possibility to use `Gson`, `Jackson` or create your own handler.([#432](https://github.com/meilisearch/meilisearch-java/pull/432))  [@alallema](https://github.com/alallema)
    * Rewrite some missing method (#473) [@alallema](https://github.com/alallema)
        * health()
        * isHealthy()
        * getVersion()
        * getStats()
        * index.getStats()
        * updateKey() ([#476](https://github.com/meilisearch/meilisearch-java/pull/476)) [@alallema](https://github.com/alallema)
    * Add typo tolerance settings ([#371](https://github.com/meilisearch/meilisearch-java/pull/371)) [@alallema](https://github.com/alallema)
    * Add toString method to SearchRequest Class ([#451](https://github.com/meilisearch/meilisearch-java/pull/451)) [@alallema](https://github.com/alallema)
    * Add patch HTTP method ([#472](https://github.com/meilisearch/meilisearch-java/pull/472)) [@alallema](https://github.com/alallema)

Thanks again to @alallema,  @brunoocasali,   @ghousek1, @kisaga ! 🎉

2022-11-09 17:51 UTC, brunoocasali requested changes

2022-11-09 17:51 UTC, brunoocasali commented on build.gradle
> +		showStandardStreams = true
This should be committed?

2022-11-09 17:51 UTC, brunoocasali commented on .code-samples.meilisearch.yaml
> -    <version>0.7.2</version>
I also think you can add to the changelog that you removed some classes like `GenericServiceTemplate`, `Dump`, `DumpHandler`, `MeilisearchHttpRequest`, and others...  

The users will search your CHANGELOG for keywords like "why the class I was using does not exist anymore?". "Now this is the new way to use the methodABC" and so on (like you did for the exception classes)...

2022-11-10 12:19 UTC, brunoocasali approved these changes
@alallema let's merge this! 🎉

2022-11-14 10:49 UTC, alallema commented
bors merge

2022-11-14 10:51 UTC, merged

2026-02-12 16:13 UTC, 07heco commented
I'd like to work on this issue.