Fix Java-doc comment
meilisearch/meilisearch-java pull request #490
Opened 2022-11-10 09:38 UTC by alallema

2022-11-10 10:44 UTC, bidoubiwa requested changes

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/Documents.java
> + * <p>https://docs.meilisearch.com/reference/api/documents.html
```suggestion
 * <p>https://docs.meilisearch.com/reference/api/documents.html</p>
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/IndexesHandler.java
> + * <p>https://docs.meilisearch.com/reference/api/indexes.html
```suggestion
 * <p>https://docs.meilisearch.com/reference/api/indexes.html</p>
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/InstanceHandler.java
> + * <p>https://docs.meilisearch.com/reference/api/keys.html
```suggestion
 * <p>https://docs.meilisearch.com/reference/api/keys.html</p>
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/KeysHandler.java
> + * <p>https://docs.meilisearch.com/reference/api/keys.html
```suggestion
 * <p>https://docs.meilisearch.com/reference/api/keys.html</p>
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/Search.java
> + * <p>https://docs.meilisearch.com/reference/api/search.html
```suggestion
 * <p>https://docs.meilisearch.com/reference/api/search.html</p>
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/Search.java
> + * Wrapper around HttpClient class to use for Meilisearch search
```suggestion
 * Search Object for searching on indexes
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/InstanceHandler.java
> + * Wrapper around HttpClient class to use for Meilisearch
Are you sure about this comment?

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/SettingsHandler.java
> + * <p>https://docs.meilisearch.com/reference/api/settings.html
```suggestion
 * <p>https://docs.meilisearch.com/reference/api/settings.html</p>
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/TasksHandler.java
> + * <p>https://docs.meilisearch.com/reference/api/tasks.html
```suggestion
 * <p>https://docs.meilisearch.com/reference/api/tasks.html</p>
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/exceptions/APIError.java
> +/** This class wraps errors sent by Meilisearch API */
```suggestion
/** Meilisearch API error wrapper */
```

```suggestion
/** Wrapper around Meilisearch API errors */
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/exceptions/MeilisearchCommunicationException.java
> +/** This class wraps MeilisearchExceptions dealing with Communication errors */
```suggestion
/** Wrapper arround MeilisearchExceptions dealing with Communication errors */
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/exceptions/MeilisearchException.java
> +/** This is a generic class for Meilisearch Exception handling */
```suggestion
/** Generic class for Meilisearch Exception handling */
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/exceptions/MeilisearchTimeoutException.java
> +/** This class wraps MeilisearchExceptions dealing with Timeout errors */
```suggestion
/** Wrapper around MeilisearchExceptions dealing with Timeout errors */
```

2022-11-10 10:44 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/model/SearchResult.java
> + * Data Structure of Meilisearch response for Result of Search
```suggestion
 * Data Structure of Meilisearch response for results of search
```

2022-11-10 10:53 UTC, alallema commented on src/main/java/com/meilisearch/sdk/Documents.java
> + * <p>https://docs.meilisearch.com/reference/api/documents.html
(https://meilisearch.slack.com/archives/D01T5TK2XN2/p1668076946171329)
https://checkstyle.sourceforge.io/config_javadoc.html#JavadocParagraph

2022-11-10 12:17 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/IndexesHandler.java
> + * Wrapper around HttpClient class to use for Meilisearch indexes
Is it necessary to say that it wraps httpClient? Woulnd't it not be better to just state that it is the `Indexes API` ?

```suggestion
 * Meilisearch Indexes class
```

```suggestion
 * Indexes class covering all the methods related to an index
```

2022-11-14 09:55 UTC, bidoubiwa requested changes

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/HttpClient.java
> +/** HTTP client to be used for the different functions to be performed through Meilisearch */
```suggestion
/** HTTP client used for API calls to Meilisearch */
```

I don't think it ads value to add more information. On the contrary, it confuses more.

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/Documents.java
> + * Documents class covering all the methods related to documents
```suggestion
 * Class covering the Meilisearch Document API
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/IndexesHandler.java
> + * IndexesHandler class covering all the methods related to an index
Documents, which covers the documents API, is called `documents` but indexes, is cal.ed `IndexesHandler`. Is there a reason?

```suggestion
 * Class covering the Meilisearch Index API.
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/KeysHandler.java
> + * Keys class covering all the methods related to keys
```suggestion
 * Class covering the Meilisearch Key API
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/Search.java
> + * Search Object for searching on indexes
```suggestion
 * Class used for searching on Meilisearch indexes
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/InstanceHandler.java
> + * Wrapper around HttpClient class to get Meilisearch instance information
```suggestion
 * Class providing information on the Meilisearch instance
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/SettingsHandler.java
>   * Settings Handler for manipulation of an Index {@link Settings}
```suggestion
 * Class covering the Meilisearch Settings API {@link Settings}
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/TasksHandler.java
> + * Task class covering all the methods related to tasks
```suggestion
 * Class covering the Meilisearch Task API
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/model/IndexStats.java
> + * Data structure of Meilisearch response for the Stats of an Index
```suggestion
 * Stats data structure of a Meilisearch Index
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/model/SearchResult.java
> + * Data Structure of Meilisearch response for results of search
```suggestion
 * Meilisearch search response data structure
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/model/Settings.java
> + * Data Structure of Meilisearch response for the Settings
```suggestion
 * Meilisearch settings data structure
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/model/Stats.java
> + * Data structure of Meilisearch response for the Stats
```suggestion
 * Meilisearch stats data structure
```

2022-11-14 09:55 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/model/TaskDetails.java
> +/** Data structure for the Details field in a Task */
```suggestion
/** Task details data structure */
```

2022-11-14 10:27 UTC, bidoubiwa commented on src/main/java/com/meilisearch/sdk/model/TypoTolerance.java
> + * Data structure of Meilisearch response for the Typo Tolerance Setting
```suggestion
 * Typo Tolerance setting data structure
```

2022-11-14 10:28 UTC, bidoubiwa approved these changes
LGTM 🔥

2022-11-14 10:30 UTC, alallema commented
bors merge

2022-11-14 10:33 UTC, merged