Add similar documents query to index
meilisearch/meilisearch-java pull request #761
Opened 2024-08-02 01:23 UTC by jdvalenzuelah

# Pull Request

## Related issue
Fixes #755

## What does this PR do?
- Add similar documents method to index

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-08-07 13:05 UTC, curquiza requested changes
Hello @jdvalenzuelah 

can you fix your test `testSimilarDocuments`? The CI is red right now 😊

2024-08-08 22:50 UTC, jdvalenzuelah commented
Hi @curquiza is there a way to get a full stacktrace in this run? Test are passing for me locally and don't really understand where the exception is coming from.

2024-08-13 16:21 UTC, curquiza commented
@jdvalenzuelah 

Looks like there is an issue in the test you created: 

```
 SearchTest > testSimilarDocuments() FAILED
    java.lang.ClassCastException at SearchTest.java:849
```

2024-08-14 17:18 UTC, jdvalenzuelah commented
Hi @curquiza I think test should work in CI now. 

When running locally i enable `vectorStore` using curl but that will obviously not be enabled in the image used in CI.

2024-08-15 12:12 UTC, curquiza commented
Hello @jdvalenzuelah 
The tests still don't pass, including the linter.
You can click on them to have more information

<img width="1043" alt="Capture d’écran 2024-08-15 à 14 11 44" src="https://github.com/user-attachments/assets/59b658bb-b36f-4ae4-b26f-8c864c810bf0">

2024-08-15 17:46 UTC, jdvalenzuelah commented
> Hello @jdvalenzuelah The tests still don't pass, including the linter. You can click on them to have more information
> <img alt="Capture d’écran 2024-08-15 à 14 11 44" width="1043" src="https://private-user-images.githubusercontent.com/20380692/358214332-59b658bb-b36f-4ae4-b26f-8c864c810bf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDQyMjEsIm5iZiI6MTcyMzc0MzkyMSwicGF0aCI6Ii8yMDM4MDY5Mi8zNTgyMTQzMzItNTliNjU4YmItYjM2Zi00YWU0LWIyNmYtOGM4NjRjODEwYmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE3NDUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMjVmZTg1MmNmYmZmODRkYjM2Nzc0MmU3ZmY2ZWFmYzA2MzJjM2IwMWZlMzg1NzlhYTFiZjdjZGVkZGJkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UL3w-1egO3gmB-nmh3_OYdUer-WH9jjbxVqgiOS2wFA">

Fixed the linter errors. The tests did not run because the `spotlessCheck` task failed.

2024-08-20 13:39 UTC, curquiza requested changes
Nice

2024-08-20 13:39 UTC, curquiza commented on .code-samples.meilisearch.yaml
> +  SimilarDocumentRequest query =  new SimilarDocumentRequest()
```suggestion
  SimilarDocumentRequest query = new SimilarDocumentRequest()
```

2024-08-20 13:39 UTC, curquiza approved these changes
bors merge

2024-08-20 13:41 UTC, merged